name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Project Checkout
      uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean assembleDebug --stacktrace

    - name: Run tests
      run: ./gradlew testDebugUnitTest --stacktrace


  androidTest:
    name: Android test
    needs: build-and-test
    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
    timeout-minutes: 45
    strategy:
      matrix:
        api-level: [ 21, 29 ]

    steps:
      - name: Project Checkout
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          disable-animations: true
          disk-size: 1500M
          heap-size: 512M
          script: ./gradlew clean :app:connectedAndroidTest --stacktrace